version: '3.7'
services:
    bodypix:
        image: bodypix
        init: true
        build:
            context: ./bodypix
        networks:
            - fakecam
        read_only: true
        ports:
            - ${PORT_BODYPIX}:9000

    fakecam:
        image: fakecam
        init: true
        build:
            context: ./fakecam
        networks:
            - fakecam
        read_only: true
        volumes:
          - ./background.jpg:/src/background.jpg:ro
        #   - /path/to/foreground.jpg:/src/foreground.jpg:ro
        #   - /path/to/foreground-mask.png:/src/foreground-mask.png:ro
        devices:
            # input (webcam)
            - /dev/video0:/dev/video0
            # output (virtual webcam)
            - /dev/video4:/dev/video2
        depends_on:
            - bodypix
        command: ["--bodypix-url", "http://bodypix:9000/",
                  "-b", "background-custom", "-f", "foreground-custom" , "-m", "foreground-mask-custom",
                  "--webcam-path", "/dev/video0", "--v4l2loopback-path", "/dev/video2"]

networks:
    fakecam:
